// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6vZUK3qYl9pqOFuhdf3A1SCmak6AmjLQ',
    appId: '1:29001474789:web:1791fa8194143ad6c22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    authDomain: 'alphaflow-69.firebaseapp.com',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    measurementId: 'G-V97SZZYN4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwcpFYGDCEm8oYxWlZV78bWJCSneOG5c',
    appId: '1:29001474789:android:53e96305dd095cfec22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    storageBucket: 'alphaflow-69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zeKSF4fl6bbQN2Qyw2SBtz9WnMFpt3s',
    appId: '1:29001474789:ios:51d0f0baf70cacd1c22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    iosBundleId: 'com.example.alphaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zeKSF4fl6bbQN2Qyw2SBtz9WnMFpt3s',
    appId: '1:29001474789:ios:51d0f0baf70cacd1c22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    iosBundleId: 'com.example.alphaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6vZUK3qYl9pqOFuhdf3A1SCmak6AmjLQ',
    appId: '1:29001474789:web:d98b1262ba0ccf95c22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    authDomain: 'alphaflow-69.firebaseapp.com',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    measurementId: 'G-753RE4GZ9F',
  );
}
