// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// blackmere:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6vZUK3qYl9pqOFuhdf3A1SCmak6AmjLQ',
    appId: '1:29001474789:web:04a5f7caf843fa6dc22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    authDomain: 'alphaflow-69.firebaseapp.com',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    measurementId: 'G-HH67FVFV5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwcpFYGDCEm8oYxWlZV78bWJCSneOG5c',
    appId: '1:29001474789:android:3bcad57e3a2b0573c22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    storageBucket: 'alphaflow-69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zeKSF4fl6bbQN2Qyw2SBtz9WnMFpt3s',
    appId: '1:29001474789:ios:86ba3167e95d393dc22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    iosBundleId: 'com.blackmere.alphaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zeKSF4fl6bbQN2Qyw2SBtz9WnMFpt3s',
    appId: '1:29001474789:ios:86ba3167e95d393dc22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    iosBundleId: 'com.blackmere.alphaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6vZUK3qYl9pqOFuhdf3A1SCmak6AmjLQ',
    appId: '1:29001474789:web:0d70e61cd5410741c22a0c',
    messagingSenderId: '29001474789',
    projectId: 'alphaflow-69',
    authDomain: 'alphaflow-69.firebaseapp.com',
    storageBucket: 'alphaflow-69.firebasestorage.app',
    measurementId: 'G-DTDHFQPMGM',
  );

}